name: QA

on:
   workflow_dispatch:
    inputs:
      aws-account-id:
        type: string
        description: AWS Account ID
        default: "373456726732"

jobs:
  deploy-json-schemas:
    environment: QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Current Schemas
        run: 
          node index.js ${{ secrets.GH_PAT }} qa ${{ secrets.BASIC_AUTH }}
